### ISSUE TITLE
Forum dump

### ISSUE THREAD

**Issue by noescape00** [mprep-btc/Unofficial-Bitcointalk-API#1]
Hello. 
Since there is no PM on GitHub I'm writing you here. 

If you have a forum dump maybe you can share it? It takes weeks to download all threads without adding bunch of proxy.

**Comment by mprep-btc** [comment]
Sorry, but I don't have anything of sort. Next time, if you need to contact me, PM me on Bitcointalk (user 'mprep').

**Comment by noescape00** [comment]
Nevermind, already parsed all I needed =)
